### ISSUE TITLE
Deadlock encountered when running Random Read benchmark

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/badger-bench#4] opened 2017-08-10 06:34 UTC
Running benchmarks using this code: https://github.com/dgraph-io/badger-bench/tree/76c540f3712c6a807dd2a29cb84104fdfbde9c9b

```
$ go test -v --bench BenchmarkReadRandomBadger --keys_mil 5 --valsz 16384 --dir "/mnt/data/16kb" --timeout 10m --benchtime 3m
/mnt/data/16kb/badger
BenchmarkReadRandomBadger/badger-random-read-128                10000000             22329 ns/op
SIGQUIT: quit
PC=0x463a41 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xd869d0, 0x0, 0x0, 0x0, 0x9800000000, 0x0, 0x0, 0x0, 0x7ffdec49c068, 0x41718b, ...)
        /usr/lib/go-1.8/src/runtime/sys_linux_amd64.s:425 +0x21
runtime.futexsleep(0xd869d0, 0x0, 0xffffffffffffffff)
        /usr/lib/go-1.8/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0xd869d0)
        /usr/lib/go-1.8/src/runtime/lock_futex.go:145 +0x6b
runtime.stopm()
        /usr/lib/go-1.8/src/runtime/proc.go:1650 +0xad
runtime.findrunnable(0xc4200ad900, 0x0)
        /usr/lib/go-1.8/src/runtime/proc.go:2102 +0x2e4
runtime.schedule()
        /usr/lib/go-1.8/src/runtime/proc.go:2222 +0x14c
runtime.goexit0(0xc428568000)
        /usr/lib/go-1.8/src/runtime/proc.go:2359 +0x238
runtime.mcall(0x7ffdec49c1f0)
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:269 +0x5b

goroutine 1 [chan receive, 10 minutes]:
testing.(*B).run1(0xc420148000, 0xc420148000)
        /usr/lib/go-1.8/src/testing/benchmark.go:215 +0xac
testing.(*B).Run(0xc420148c60, 0x92fa25, 0x19, 0x941d70, 0x4ea800)
        /usr/lib/go-1.8/src/testing/benchmark.go:493 +0x1d5
testing.runBenchmarks.func1(0xc420148c60)
        /usr/lib/go-1.8/src/testing/benchmark.go:403 +0x67
testing.(*B).runN(0xc420148c60, 0x1)
        /usr/lib/go-1.8/src/testing/benchmark.go:140 +0xb2
testing.runBenchmarks(0xc420224060, 0xd52700, 0x7, 0x7, 0xc4201e0100)
        /usr/lib/go-1.8/src/testing/benchmark.go:409 +0x48d
testing.(*M).Run(0xc4200e5f20, 0x942c10)
        /usr/lib/go-1.8/src/testing/testing.go:828 +0x305
github.com/dgraph-io/badger-bench.TestMain(0xc4200e5f20)
        /home/ubuntu/go/src/github.com/dgraph-io/badger-bench/bench_test.go:382 +0x6f
main.main()
        github.com/dgraph-io/badger-bench/_test/_testmain.go:52 +0xf7

goroutine 17 [syscall, 10 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 8 [chan receive]:
github.com/dgraph-io/dgraph/x.init.2.func1(0xc42001db40)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/x/metrics.go:93 +0x4c
created by github.com/dgraph-io/dgraph/x.init.2
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/x/metrics.go:101 +0x4fc

goroutine 14 [IO wait, 10 minutes]:
net.runtime_pollWait(0x7f6ef4efdf00, 0x72, 0x0)
        /usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200f0068, 0x72, 0x0, 0xc420188e80)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200f0068, 0xffffffffffffffff, 0x0)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4200f0000, 0x0, 0xd5ad20, 0xc420188e80)
        /usr/lib/go-1.8/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42015a000, 0xc42001e4b0, 0xc4200d0e78, 0x55092d)
        /usr/lib/go-1.8/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42015a000, 0x6bc1a3, 0xc4200d0e90, 0xc4200d0e88)
        /usr/lib/go-1.8/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42015a000, 0xc42001e450, 0x894720, 0xd4b100, 0x8da1c0)
        /usr/lib/go-1.8/src/net/http/server.go:3044 +0x2f
net/http.(*Server).Serve(0xc420226000, 0xd5fee0, 0xc42015a000, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServe(0xc420226000, 0xc420226000, 0xc4201e0f50)
        /usr/lib/go-1.8/src/net/http/server.go:2585 +0xb0
net/http.ListenAndServe(0x922496, 0x5, 0x0, 0x0, 0xda2578, 0x8d9680)
        /usr/lib/go-1.8/src/net/http/server.go:2787 +0x7f
created by github.com/dgraph-io/badger-bench.TestMain
        /home/ubuntu/go/src/github.com/dgraph-io/badger-bench/bench_test.go:381 +0x61

goroutine 16 [semacquire, 6 minutes]:
sync.runtime_Semacquire(0xc42fc469bc)
        /usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc42fc469b0)
        /usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger/y.(*LevelCloser).Wait(0xc42fc46990)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/y/y.go:189 +0x31
github.com/dgraph-io/badger.(*KV).Close(0xc420132000, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:393 +0x1f3
github.com/dgraph-io/badger-bench.BenchmarkReadRandomBadger(0xc420148000)
        /home/ubuntu/go/src/github.com/dgraph-io/badger-bench/bench_test.go:156 +0x131
testing.(*B).runN(0xc420148000, 0x1)
        /usr/lib/go-1.8/src/testing/benchmark.go:140 +0xb2
testing.(*B).run1.func1(0xc420148000)
        /usr/lib/go-1.8/src/testing/benchmark.go:213 +0x5a
created by testing.(*B).run1
        /usr/lib/go-1.8/src/testing/benchmark.go:214 +0x7f

goroutine 18 [chan receive, 2 minutes]:
github.com/dgraph-io/badger.(*KV).updateSize(0xc420132000)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:1135 +0x88
created by github.com/dgraph-io/badger.NewKV
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:218 +0xa8b

goroutine 42725 [runnable]:
time.Sleep(0x989680)
        /usr/lib/go-1.8/src/runtime/time.go:59 +0xf9
github.com/dgraph-io/badger.(*levelsController).addLevel0Table(0xc424c26000, 0xc42fd54540, 0xc42fd54540, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/levels.go:632 +0x502
github.com/dgraph-io/badger.(*KV).flushMemtable(0xc420132000, 0xc42fc46990, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:1081 +0x362
created by github.com/dgraph-io/badger.NewKV
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:230 +0xc3c

rax    0xca
rbx    0x0
rcx    0x463a43
rdx    0x0
rdi    0xd869d0
rsi    0x0
rbp    0x7ffdec49c038
rsp    0x7ffdec49bff0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0xffffffee
r14    0xd800
r15    0x4
rip    0x463a41
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
FAIL    github.com/dgraph-io/badger-bench       660.043s
```

**Comment by deepakjois** [comment] 2017-08-10 10:07
happened with this code as well: https://github.com/dgraph-io/badger-bench/tree/f76a4ffdf3f1e313fa2384624cd24bf124aa6765

```
ubuntu@ip-172-31-39-80:~/go/src/github.com/dgraph-io/badger-bench$ go test -v --bench BenchmarkReadRandomBadger --keys_mil 5 --valsz 16384 --dir "/mnt/data/16kb" --timeout 10m --benchtime 3m
/mnt/data/16kb/badger
BenchmarkReadRandomBadger/read-random-badger-128                10000000             22608 ns/op
SIGQUIT: quit
PC=0x463a41 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xd86990, 0x0, 0x0, 0x0, 0x0, 0xd85c60, 0x0, 0x0, 0x7ffc07984b38, 0x41718b, ...)
        /usr/lib/go-1.8/src/runtime/sys_linux_amd64.s:425 +0x21
runtime.futexsleep(0xd86990, 0x0, 0xffffffffffffffff)
        /usr/lib/go-1.8/src/runtime/os_linux.go:45 +0x62
runtime.notesleep(0xd86990)
        /usr/lib/go-1.8/src/runtime/lock_futex.go:145 +0x6b
runtime.stopm()
        /usr/lib/go-1.8/src/runtime/proc.go:1650 +0xad
runtime.findrunnable(0xc420040600, 0x0)
        /usr/lib/go-1.8/src/runtime/proc.go:2102 +0x2e4
runtime.schedule()
        /usr/lib/go-1.8/src/runtime/proc.go:2222 +0x14c
runtime.goexit0(0xc4289161a0)
        /usr/lib/go-1.8/src/runtime/proc.go:2359 +0x238
runtime.mcall(0x7ffc07984cc0)
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:269 +0x5b

goroutine 1 [chan receive, 10 minutes]:
testing.(*B).run1(0xc420148000, 0xc420148000)
        /usr/lib/go-1.8/src/testing/benchmark.go:215 +0xac
testing.(*B).Run(0xc420148c60, 0x930171, 0x19, 0x942588, 0x4ea800)
        /usr/lib/go-1.8/src/testing/benchmark.go:493 +0x1d5
testing.runBenchmarks.func1(0xc420148c60)
        /usr/lib/go-1.8/src/testing/benchmark.go:403 +0x67
testing.(*B).runN(0xc420148c60, 0x1)
        /usr/lib/go-1.8/src/testing/benchmark.go:140 +0xb2
testing.runBenchmarks(0xc420224080, 0xd52700, 0x7, 0x7, 0xc4201e0100)
        /usr/lib/go-1.8/src/testing/benchmark.go:409 +0x48d
testing.(*M).Run(0xc4200e5f20, 0x943428)
        /usr/lib/go-1.8/src/testing/testing.go:828 +0x305
github.com/dgraph-io/badger-bench.TestMain(0xc4200e5f20)
        /home/ubuntu/go/src/github.com/dgraph-io/badger-bench/bench_test.go:343 +0x6f
main.main()
        github.com/dgraph-io/badger-bench/_test/_testmain.go:52 +0xf7

goroutine 17 [syscall, 10 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 8 [chan receive]:
github.com/dgraph-io/dgraph/x.init.2.func1(0xc420017b80)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/x/metrics.go:93 +0x4c
created by github.com/dgraph-io/dgraph/x.init.2
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/x/metrics.go:101 +0x4fc

goroutine 14 [IO wait, 10 minutes]:
net.runtime_pollWait(0x7f7b3e967700, 0x72, 0x0)
        /usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200f0068, 0x72, 0x0, 0xc420188ea0)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200f0068, 0xffffffffffffffff, 0x0)
        /usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4200f0000, 0x0, 0xd5ad20, 0xc420188ea0)
        /usr/lib/go-1.8/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42015a000, 0xc42001e480, 0xc4200d0e78, 0x55092d)
        /usr/lib/go-1.8/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42015a000, 0x6bc1a3, 0xc4200d0e90, 0xc4200d0e88)
        /usr/lib/go-1.8/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42015a000, 0xc42001e420, 0x894d00, 0xd4b100, 0x8da520)
        /usr/lib/go-1.8/src/net/http/server.go:3044 +0x2f
net/http.(*Server).Serve(0xc420226000, 0xd5fea0, 0xc42015a000, 0x0, 0x0)
        /usr/lib/go-1.8/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServe(0xc420226000, 0xc420226000, 0xc4201e0f50)
        /usr/lib/go-1.8/src/net/http/server.go:2585 +0xb0
net/http.ListenAndServe(0x922bd2, 0x5, 0x0, 0x0, 0xda2538, 0x8d99e0)
        /usr/lib/go-1.8/src/net/http/server.go:2787 +0x7f
created by github.com/dgraph-io/badger-bench.TestMain
        /home/ubuntu/go/src/github.com/dgraph-io/badger-bench/bench_test.go:342 +0x61

goroutine 16 [semacquire, 6 minutes]:
sync.runtime_Semacquire(0xc42ffbc23c)
        /usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc42ffbc230)
        /usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger/y.(*LevelCloser).Wait(0xc42ffbc210)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/y/y.go:189 +0x31
github.com/dgraph-io/badger.(*KV).Close(0xc420132000, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:393 +0x1f3
github.com/dgraph-io/badger-bench.BenchmarkReadRandomBadger(0xc420148000)
        /home/ubuntu/go/src/github.com/dgraph-io/badger-bench/bench_test.go:111 +0x50b
testing.(*B).runN(0xc420148000, 0x1)
        /usr/lib/go-1.8/src/testing/benchmark.go:140 +0xb2
testing.(*B).run1.func1(0xc420148000)
        /usr/lib/go-1.8/src/testing/benchmark.go:213 +0x5a
created by testing.(*B).run1
        /usr/lib/go-1.8/src/testing/benchmark.go:214 +0x7f

goroutine 18 [chan receive, 2 minutes]:
github.com/dgraph-io/badger.(*KV).updateSize(0xc420132000)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:1139 +0x88
created by github.com/dgraph-io/badger.NewKV
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:218 +0xa8b

goroutine 42709 [runnable]:
time.Sleep(0x989680)
        /usr/lib/go-1.8/src/runtime/time.go:59 +0xf9
github.com/dgraph-io/badger.(*levelsController).addLevel0Table(0xc424c26000, 0xc42ffb8380, 0xc42ffb8380, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/levels.go:632 +0x502
github.com/dgraph-io/badger.(*KV).flushMemtable(0xc420132000, 0xc42ffbc210, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:1085 +0x362
created by github.com/dgraph-io/badger.NewKV
        /home/ubuntu/go/src/github.com/dgraph-io/badger/kv.go:230 +0xc3c

rax    0xca
rbx    0x0
rcx    0x463a43
rdx    0x0
rdi    0xd86990
rsi    0x0
rbp    0x7ffc07984b08
rsp    0x7ffc07984ac0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x7a3773a8e5fb76c5
r13    0x4
r14    0x0
r15    0xd2
rip    0x463a41
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (11m0s).
FAIL    github.com/dgraph-io/badger-bench       660.047s
```

**Comment by deepakjois** [comment] 2017-08-10 10:10
Once this happens, I can’t even run it with default `--timeout` and `--benchtime` values. The last time it happened, I had to repopulate the data before I could resume benchmarking badger again

```
go test -v --bench BenchmarkReadRandomBadger --keys_mil 5 --valsz 16384 --dir "/mnt/data/16kb"
/mnt/data/16kb/badger
BenchmarkReadRandomBadger/read-random-badger-128                  100000             19525 ns/op

…<hangs>…

```

and it hangs there and produces output similar to above.

**Comment by manishrjain** [comment] 2017-08-11 01:59
This issue really belongs to Badger repo. But, it's already here now.

**Comment by srh** [comment] 2017-08-11 05:45
I reproduce this in badger-bench master too.  If you run the ReadRandomBadger benchmark enough times, you'll add in more and more sst files.  Then `addLevel0Table` infinite-loops, because ` len(s.tables) >= s.kv.opt.NumLevelZeroTablesStall` in its callee `tryAddLevel0Table` is true.

I recently changed the inequality there in Badger from >= to >.  Undoing that doesn't change anything.

Anyway, I'm in the midst of fixing this.

**Comment by srh** [comment] 2017-08-14 00:58
It's just because we have DoNotCompact = true set in `getBadger`.

Thus, because we flush memtables despite having a read-only workload, we eventually create too many memtables in level zero.

Going to treat this as a dupe of https://github.com/dgraph-io/badger/issues/156 .

**Closed by srh** 2017-08-14 00:58 UTC
Labels: bug
